### ISSUE TITLE
בדיקה למה השאילתה של ההבאת טיולים לאחר בחירת ג'אנרים ככ כבדה

### ISSUE THREAD

**Issue by TamarZanzouri** [haimyyy/tripper#20]

**Comment by haimyyy** [comment]
נוכל לעשות את זה מבלי לבזבז זמם או אחרי השיעור של יונית או אחרי הבאטה.

**Comment by haimyyy** [comment]
הכוונה השיעור של יונית על מונגו לדעת מה אנחנו עושים לא יעיל \ לא נכון
